### PR TITLE
Allow to read memory slices of unknown size at compile time

### PR DESCRIPTION
**Pull request by Jujstme**

### CODE REVIEW

**Comment by CryZe** [comment]
Mmh, I wonder if it would be better to provide the vector as a `vec: &mut Vec<T>`, where it then is able to reuse the allocation at least.

**Comment by Jujstme** [comment]
I don't follow. Vec's ownership just gets moved.

**Comment by Jujstme** [comment]
> Mmh, I wonder if it would be better to provide the vector as a `vec: &mut Vec<T>`, where it then is able to reuse the allocation at least.

It's possible but it means the user will be limited by the `capacity()` provided when instancing the Vec.
I can probably provide both methods.

**Comment by Jujstme** [comment]
`read_into_vec()` has now been updated in order to use `reserve(`), this way the `Vec` is guaranteed to have the capacity needed to read from memory the amount of data specified in the method call

**Pull request merged**
